---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-user
rules:
  - apiGroups:
    - "apps"
    - ""
    resources:
    - pods
    - pods/exec
    - services
    - deployments
    - configmaps
    - secrets
    - horizontalpodautoscalers
    verbs:
    - get
    - list
    - create
    - update
    - patch
    - watch
    - delete
    - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-user
subjects:
- kind: User
  name: belenot.com