# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.raw_ssh_args = ['-o StrictHostKeyChecking=no']
    ansible.vault_password_file = "password"
  end

  config.vm.network "private_network", ip: "192.168.52.10"

end
